# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseofferforsalehistory',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='houseofferforsalehistory',
            name='correspondagent',
            field=models.CharField(blank=True, db_column='CorrespondaAgency', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='houseofferforsalehistory',
            name='correspondagentstores',
            field=models.CharField(blank=True, db_column='CorrespondaAgentStores', max_length=255, null=True),
        ),
    ]
