# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='SyncHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='houseofferforsalehistory',
            name='house_status',
            field=models.CharField(blank=True, db_column='HouseStatus', max_length=64, null=True),
        ),
    ]
