# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20170322_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseofferforsalehistory',
            name='correspondagent',
            field=models.CharField(blank=True, db_column='CorrespondaAgency', max_length=255, null=True, verbose_name='\u5bf9\u5e94\u4e2d\u4ecb\u673a\u6784'),
        ),
        migrations.AlterField(
            model_name='houseofferforsalehistory',
            name='correspondagentstores',
            field=models.CharField(blank=True, db_column='CorrespondaAgentStores', max_length=255, null=True, verbose_name='\u5bf9\u5e94\u4e2d\u4ecb\u95e8\u5e97'),
        ),
    ]
