# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_sendtaskhistory_synchouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZhongJieMingCheng', models.CharField(blank=True, max_length=128, null=True, verbose_name='中介名称')),
                ('MenDianShu', models.IntegerField(blank=True, default=0, null=True, verbose_name='门店数')),
                ('JingJiRenShu', models.IntegerField(blank=True, max_length=128, null=True, verbose_name='经纪人数量')),
                ('XinZengGongYingShu', models.IntegerField(blank=True, max_length=128, null=True, verbose_name='新增二手房供应数量')),
                ('ShiJian', models.CharField(blank=True, max_length=128, null=True, verbose_name='时间')),
                ('ChengShi', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市')),
                ('XingZhengQu', models.CharField(blank=True, max_length=128, null=True, verbose_name='行政区')),
                ('PianQu', models.CharField(blank=True, max_length=128, null=True, verbose_name='片区')),
                ('YeTai', models.CharField(blank=True, max_length=128, null=True, verbose_name='业态')),
            ],
        ),
    ]
