# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_agentstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstat',
            name='JingJiRenShu',
            field=models.IntegerField(blank=True, null=True, verbose_name='经纪人数量'),
        ),
        migrations.AlterField(
            model_name='agentstat',
            name='XinZengGongYingShu',
            field=models.IntegerField(blank=True, null=True, verbose_name='新增二手房供应数量'),
        ),
    ]
