# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20170323_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='\u516c\u5bd3', max_length=128, null=True, verbose_name='\u7c7b\u578b')),
                ('chengShi', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u57ce\u5e02')),
                ('xiaoQu', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5c0f\u533a')),
                ('junJia', models.FloatField(verbose_name='\u5747\u4ef7')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
            ],
        ),
    ]
