# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_districtavg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialareaAvgPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='公寓', max_length=128, null=True, verbose_name='类型')),
                ('chengShi', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市')),
                ('xiaoQu', models.CharField(blank=True, max_length=128, null=True, verbose_name='小区')),
                ('junJia', models.FloatField(verbose_name='均价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
            ],
        ),
        migrations.DeleteModel(
            name='DistrictAvg',
        ),
    ]
