# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20170324_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialareaavgprice',
            name='xiaoQu',
        ),
        migrations.AddField(
            model_name='residentialareaavgprice',
            name='residentialareaid',
            field=models.IntegerField(default=0, verbose_name='小区id'),
        ),
    ]
